version: '3.9'

services:
  postgres:
    restart: always
    image: 'postgres:15.2'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
