version: '3.9'

services:
  postgres-local:
    extends:
      file: ../docker-compose-common.yml
      service: postgres
    ports:
      - 5432:5432
    labels:
      org.springframework.boot.service-connection: postgres-local
